// Copyright (C) 2024 Fred Emmott <fred@fredemmott.com>
// SPDX-License-Identifier: MIT
#pragma once

#if __has_include(<FredEmmott.composable_bind.config-tweaks.hpp>)
#include <FredEmmott.composable_bind.config-tweaks.hpp>
#endif

#ifndef FREDEMMOTT_COMPOSABLE_BIND_IMPLICIT_OPTIONAL_FEATURES
#define FREDEMMOTT_COMPOSABLE_BIND_IMPLICIT_OPTIONAL_FEATURES true
#endif

//-----
#ifndef FREDEMMOTT_COMPOSABLE_BIND_ENABLE_WEAK_REFS
#define FREDEMMOTT_COMPOSABLE_BIND_ENABLE_WEAK_REFS \
  FREDEMMOTT_COMPOSABLE_BIND_IMPLICIT_OPTIONAL_FEATURES
#endif

//-----
#ifndef FREDEMMOTT_COMPOSABLE_BIND_ENABLE_CPPWINRT
#if __has_include(<winrt/base.h>)
#define FREDEMMOTT_COMPOSABLE_BIND_ENABLE_CPPWINRT \
  FREDEMMOTT_COMPOSABLE_BIND_IMPLICIT_OPTIONAL_FEATURES
#else
#define FREDEMMOTT_COMPOSABLE_BIND_ENABLE_CPPWINRT false
#endif
#endif

//-----
#ifndef FREDEMMOTT_COMPOSABLE_BIND_ENABLE_BIND_BACK

#if FREDEMMOTT_COMPOSABLE_BIND_IMPLICIT_OPTIONAL_FEATURES

#include <version>
#ifdef __cpp_lib_bind_back
#define FREDEMMOTT_COMPOSABLE_BIND_ENABLE_BIND_BACK true
#else
#define FREDEMMOTT_COMPOSABLE_BIND_ENABLE_BIND_BACK false
#endif

#else// FREDEMMOTT_COMPOSABLE_BIND_IMPLICIT_OPTIONAL_FEATURES

#define FREDEMMOTT_COMPOSABLE_BIND_ENABLE_BIND_BACK false

#endif// FREDEMMOTT_COMPOSABLE_BIND_IMPLICIT_OPTIONAL_FEATURES

#endif// ifndef