repository: OpenKneeboard/OpenKneeboard
title: Bindline
description: C++ function composition through pipelines
theme: just-the-docs
permalink: pretty
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: https://github.com/fredemmott/bindline
gh_edit_branch: master
gh_edit_source: docs
gh_edit_view_mode: edit
aux_links:
  "Discord":
    - "https://go.fredemmott.com/discord"
  "GitHub":
    - "https://github.com/fredemmott/bindline"
