source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
gem "jekyll"
gem "json"
gem "just-the-docs"

group :development do
  gem "webrick"
  gem 'wdm', '>= 0.1.0' if Gem.win_platform?
end
