name: CI Matrix
on: [push, pull_request]
jobs:
  call-build-and-test:
    name: ${{matrix.os}}/${{matrix.compiler}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            runs-on: windows-2022
            compiler: cl
          - os: windows
            runs-on: windows-2022
            compiler: cl
            force-cxx-standard: 23
          - os: windows
            runs-on: windows-2022
            compiler: clang++
          - os: windows
            runs-on: windows-2022
            compiler: clang++
            force-cxx-standard: 23
          - os: windows
            runs-on: windows-2022
            compiler: clang-cl
          - os: linux
            runs-on: ubuntu-22.04
            compiler: clang++
          - os: linux
            runs-on: ubuntu-22.04
            compiler: g++
          - os: macos
            runs-on: macos-14
            compiler: clang++
    uses: ./.github/workflows/build-and-test.yml
    with:
      os: ${{matrix.os}}
      runs-on: ${{matrix.runs-on}}
      compiler: ${{matrix.compiler}}
      experimental: ${{matrix.experimental || false }}
      force-cxx-standard: ${{matrix.force-cxx-standard || 0}}
      suffix: ${{matrix.force-cxx-standard && format('C++{0}', matrix.force-cxx-standard)}}
      fs-suffix: ${{matrix.force-cxx-standard && format('cxx{0}', matrix.force-cxx-standard)}}