name: CI Matrix
on:
  push:
    branches: ["main"]
    paths:
      - 'include/**'
      - 'tests/**'
      - '**/CMakeLists.txt'
  pull_request:
    paths:
      - 'include/**'
      - 'tests/**'
      - '**/CMakeLists.txt'
jobs:
  call-build-and-test:
    name: ${{matrix.os}}/${{matrix.compiler}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            runs-on: windows-2022
            compiler: cl
          - os: windows
            runs-on: windows-2022
            compiler: cl
            force-cxx-standard: 23
            suffix: C++23
          - os: windows
            runs-on: windows-2022
            compiler: clang++
          - os: windows
            runs-on: windows-2022
            compiler: clang++
            force-cxx-standard: 23
            suffix: C++23
          - os: windows
            runs-on: windows-2022
            compiler: clang-cl
          - os: linux
            runs-on: ubuntu-22.04
            compiler: clang++
          - os: linux
            runs-on: ubuntu-22.04
            compiler: clang++
            cxx-flags: -fsanitize=address
            suffix: ASAN
          - os: linux
            runs-on: ubuntu-22.04
            compiler: clang++
            force-cxx-standard: 23
            suffix: C++23
          - os: linux
            runs-on: ubuntu-22.04
            compiler: clang++
            force-cxx-standard: 23
            cxx-flags: -fsanitize=address
            suffix: C++23/ASAN
          - os: linux
            runs-on: ubuntu-22.04
            compiler: g++
          - os: macos
            runs-on: macos-14
            compiler: clang++
    uses: ./.github/workflows/build-and-test.yml
    with:
      os: ${{matrix.os}}
      runs-on: ${{matrix.runs-on}}
      compiler: ${{matrix.compiler}}
      experimental: ${{matrix.experimental || false }}
      force-cxx-standard: ${{matrix.force-cxx-standard || 'OFF'}}
      suffix: ${{matrix.suffix && matrix.suffix || ''}}
      cxx-flags: ${{matrix.cxx-flags || ''}}